"""Validate the T01 contract and representative acceptance/rejection cases.
Run with the dependencies in validation-requirements.txt; does not run the API.
"""
import json
from pathlib import Path
from jsonschema import Draft202012Validator, FormatChecker
from openapi_spec_validator import validate

root = Path(__file__).parent
spec = json.loads((root.parent / 'contracts' / 'openapi.json').read_text())
validate(spec)
C = '/companies/{companyId}'
P = C + '/service-profiles/{profileId}'
# Independently transcribed route inventory from API v3, plus operational health.
inventory = [
 ('post', '/auth/login'), ('get', '/auth/me'), ('post', '/auth/logout'), ('post', '/auth/change-password'),
 ('post', '/auth/password-reset/request'), ('post', '/auth/password-reset/confirm'),
 ('get post', '/companies'), ('get patch', C),
 ('get post', C+'/users'), ('patch', C+'/users/{userId}'),
 ('get post', C+'/customers'), ('get patch', C+'/customers/{id}'),
 ('get post', C+'/staff'), ('get patch', C+'/staff/{id}'),
 ('get post', C+'/staff-roles'), ('delete', C+'/staff-roles/{id}'),
 ('get post', C+'/products'), ('patch', C+'/products/{id}'),
 ('get post', C+'/charges'), ('patch', C+'/charges/{id}'),
 ('get post', C+'/out-store-shops'), ('patch', C+'/out-store-shops/{id}'),
 ('get post', C+'/standby-items'), ('patch', C+'/standby-items/{id}'),
 ('post', C+'/standby-items/{id}/issue'), ('post', C+'/standby-items/{id}/return'),
 ('get post', C+'/service-profiles'), ('patch delete', P), ('get', P+'/form'),
 ('get post', P+'/fields'), ('patch delete', P+'/fields/{fieldId}'),
 ('get post', P+'/statuses'), ('patch delete', P+'/statuses/{statusId}'),
 ('put', P+'/out-store-mapping'),
 ('get post', C+'/service-requests'), ('get patch', C+'/service-requests/{id}'),
 ('patch', C+'/service-requests/{id}/status'), ('get', C+'/service-requests/{id}/history'),
 ('get post', C+'/out-store-entries'), ('get patch', C+'/out-store-entries/{id}'),
 ('post', C+'/out-store-entries/{id}/receive-back'),
 ('get head', '/health/live'), ('get head', '/health/ready'),
 # Added after v3: dashboard summary, profile options for Records filters, T28 password reset.
 ('get', '/dashboard'), ('get', C+'/service-record-options'), ('post', C+'/users/{userId}/reset-password'),
 # T36 lending history per item and across items.
 ('get', C+'/standby-items/{id}/issues'), ('get', C+'/standby-issues'),
]
expected={(p,m) for methods,p in inventory for m in methods.split()}
actual={(p,m) for p,methods in spec['paths'].items() for m in methods}
assert actual == expected, (actual-expected, expected-actual)
ids=[op['operationId'] for methods in spec['paths'].values() for op in methods.values()]
assert len(ids)==len(set(ids)), 'Duplicate operation IDs'
for path, methods in spec['paths'].items():
 for method, operation in methods.items():
  roles=operation['x-roles']
  if any(part in path for part in ['/service-requests','/out-store-entries']) or path.endswith(('/issue','/return')):
   assert set(roles)=={'ADMIN','USER'}, (method,path,roles)
  if method in {'post','put','patch','delete'} and '/auth/' not in path and not any(x in path for x in ['/service-requests','/out-store-entries']) and not path.endswith(('/issue','/return')):
   assert 'USER' not in roles, (method,path)
  if roles==['PUBLIC']:assert operation['security']==[]
  if method=='head':assert all('content' not in r for r in operation['responses'].values())

UID='11111111-1111-4111-8111-111111111111'
checks=0
def check(schema, instance, valid=True):
 global checks
 validator=Draft202012Validator({'$ref':'#/components/schemas/'+schema,'components':spec['components']},format_checker=FormatChecker())
 errors=list(validator.iter_errors(instance))
 assert bool(errors) != valid, (schema,instance, [e.message for e in errors])
 checks+=1
check('CustomerCreate',{'name':'Customer','contact':'123'})
check('CustomerCreate',{'name':'Customer'},False)
check('CustomerCreate',{'name':'Customer','contact':'123','customer_no':'C-1001'},False)
check('CustomerCreate',{'name':'Customer','contact':'123','company_id':UID},False)
check('UserCreate',{'name':'Admin','email':'admin@example.test','role':'ADMIN'})
# T28: passwords are generated by the server.
check('UserCreate',{'name':'Admin','email':'admin@example.test','password':'a long example 42','role':'ADMIN'},False)
check('UserCreate',{'name':'Admin','email':'admin@example.test','role':'SUPER_ADMIN'},False)
check('UserPatch',{},False)
check('UserCreate',{'name':'Admin','email':'admin@example.test','phone':'98765 43210','role':'ADMIN'})
check('UserPatch',{'phone':None})
check('UserPatch',{'phone':'98765abc'},False)
check('LoginRequest',{'identifier':'98765 43210','password':'x'})
check('LoginRequest',{'email':'admin@example.test','password':'x'})
check('LoginRequest',{'password':'x'},False)
check('UserPatch',{'password':'abc1234567'},False)
check('ChangePassword',{'current_password':'Tmp7xYz2abcd','new_password':'abc1234567'})
# Letter-and-number composition is enforced by the server (Go tests), not the schema.
check('ChangePassword',{'current_password':'Tmp7xYz2abcd','new_password':'short12'},False)
check('CredentialDelivery',{'email_sent':False,'temporary_password':'Tmp7xYz2abcd'})
check('CredentialDelivery',{'email_sent':True})
check('PasswordResetRequest',{'identifier':'98765 43210'})
check('ServiceRequestFacets',{'statuses':[{'status_name':'Pending','closed':False,'count':2}],'open':2,'closed':0,'creators':[{'id':UID,'name':'Owner','count':2}]})
check('PasswordResetConfirm',{'token':'A'*43,'new_password':'NewPassword9'})
check('PasswordResetConfirm',{'token':'short','new_password':'NewPassword9'},False)
company={'name':'Acme','admin':{'name':'Owner','email':'owner@example.test'}}
check('CompanyCreate',company)
check('CompanyCreate',{**company,'code':'AC'},False)
check('StaffPatch',{'role_ids':[UID,UID]},False)
check('StaffPatch',{'role_ids':[]})
check('ServiceProfileCreate',{'name':'Repair','prefix':'RF'})
check('ServiceProfileCreate',{'name':'Repair','prefix':'RF-1'},False)
check('ServiceProfilePatch',{'core_labels':{'customer_contact':'Mobile'}})
check('ServiceProfilePatch',{'core_labels':{'customer_no':'Customer ID'}},False)
check('ServiceProfilePatch',{'core_labels':{'unknown':'Invalid'}},False)
check('ProfileFieldCreate',{'key':'complaint','label':'Complaint','type':'text','config':{'multiline':True}})
check('ProfileFieldCreate',{'key':'x','label':'X','type':'choice','config':{'options':['A'],'multiple':True,'buttons':True}},False)
check('ProfileFieldCreate',{'key':'x','label':'X','type':'staff_role','config':{'role_id':UID}})
check('ProfileFieldCreate',{'key':'x','label':'X','type':'staff_role','config':{}},False)
check('ProfileFieldPatch',{'key':'changed'},False)
check('ConfigDate',{'quick_pick':True,'toggle_based':True},False)
check('Formula',{'a':'amount','op':'-','b':'advance'})
check('Formula',{'a':'amount','op':'eval','b':'advance'},False)
check('ToggleDate',{'on':True,'date':'2026-09-16'})
check('ToggleDate',{'on':True,'date':None},False)
check('ToggleDate',{'on':False,'date':None})
check('ToggleDate',{'on':True,'date':'2026-02-30'},False)
request={'profile_id':UID,'customer_id':UID,'service_date':'2026-09-16','form_data':{'complaint':'Not printing','confirmed':False,'amount':0,'choices':['A']},'out_store':{'shop_id':UID,'price':'125.00'}}
check('ServiceRequestCreate',request)
check('ServiceRequestCreate',{**request,'created_by':UID},False)
check('ServiceRequestCreate',{**request,'out_store':{'shop_id':UID,'price':'-1'}},False)
check('ServiceRequestCreate',{**request,'form_data':{'nested':{'unexpected':'object'}}},False)
new_customer = {k: v for k, v in request.items() if k != 'customer_id'}
check('ServiceRequestCreate',{**new_customer,'customer':{'name':'Ravi','contact':'98765 43210','email':None,'address':'Anna Nagar'}})
check('ServiceRequestCreate',{**request,'customer':{'name':'Ravi','contact':'9876543210'}},False)
check('ServiceRequestCreate',new_customer,False)
check('ServiceRequestCreate',{**new_customer,'customer':{'name':'Ravi'}},False)
check('OutStoreMapping',{'sent_status_id':UID,'received_status_id':UID})
check('OutStoreMapping',{'sent_status_id':UID,'received_status_id':None},False)
check('OutStoreMapping',{'sent_status_id':None,'received_status_id':None})
check('StandbyIssueCreate',{'customer_id':UID,'issued_date':'2026-09-16','received_product_id':UID})
check('StandbyReturn',{'issue_id':UID})
sent={'event':'sent','entry_id':UID,'shop_id':UID,'shop_name':'Vendor','sent_date':'2026-09-16','due_date':None,'price':'125.50','remarks':None,'received_back_at':None}
check('HistoryOutStoreValue',sent)
check('HistoryOutStoreValue',{k:v for k,v in sent.items() if k!='event'})
check('HistoryOutStoreValue',{**sent,'event':'deleted'},False)
lent={'event':'returned','issue_id':UID,'standby_item_id':UID,'item_name':'Loaner','serial_no':None,'customer_name':'Ravi','customer_contact':'98765 43210','issued_date':'2026-09-16','due_date':None,'returned_at':'2026-09-20T10:00:00Z','days_out':4}
check('HistoryStandbyValue',lent)
check('HistoryStandbyValue',{**lent,'days_out':-1},False)
issue={'id':UID,'company_id':UID,'standby_item_id':UID,'customer_id':UID,'service_request_id':None,'issued_date':'2026-09-16','due_date':None,'returned_at':None,'notes':None,'received_product_id':None,'issued_by':UID,'returned_by':None}
check('StandbyIssue',issue)
check('StandbyIssueHistory',{**issue,'item_name':'Loaner','serial_no':'SL-1','customer_name':'Ravi','customer_contact':'98765 43210','request_no':None,'issued_by_name':'Owner','returned_by_name':None,'days_out':3,'overdue':False})
check('StandbyIssueHistory',issue,False)
check('StandbyReturn',{},False)
check('StandbyItemPatch',{'status':'ISSUED'},False)
check('StandbyItemPatch',{'status':'UNDER_MAINTENANCE'})
print(f'OpenAPI valid; {len(actual)} operations match source inventory; role checks and {checks} schema cases passed.')
